### ISSUE TITLE
Add WEB3 feature to interact with DApps in this browser

### ISSUE THREAD

**Issue by ronaldoguedess** [HarshAndroid/Lets_Browse#1]
What do you think about adding the Web3 in your browser?
It will be perfect... Your videos help me a lot, and I love seeing you implement it.

I'm developing a Dapp browser with Web3, and I'm facing problems injecting the javascript, I'm new to it, but I'm sure that it will be easy for you, so I will learn and make it with you.

**This is the GitHub about the Trust Wallet Web3-Provider.**
https://github.com/trustwallet/trust-web3-provider

before I forget, congratulations!

if you have doubts about the web3 browser I could teach you something.

**Comment by HarshAndroid** [comment]
First of all thanks for compliment.

And regarding web3, actually I've just heard that it's the 3rd generation of web (and some more stuff about it) but don't have any hands on experience regarding it & also haven't worked much with javascript injection.

I would love to help you but nowadays I'm not getting enough time (I'm a working professional & youtuber, etc.).

So I hope you will understand my situation.

**Comment by ronaldoguedess** [comment]
No problem, I understand. hahahthanks so much for reppling me...
Yep, this is the 3rd generation of web.
I'm building here my browser web3, and your videos are helping me a lot, when I finish I will contact you to show you!
thanks so much!
